title: napari-roidynamics
author: Ana Stojiljkovic and Guillaume Witz
logo: docs/images/napari-roidynamics_logo.png

execute:
  execute_notebooks: 'off'

sphinx:
  config:
    html_extra_path: ['.','docs/images']